export const paths = {
  home: '/',
  auth: { signIn: '/auth/sign-in', signUp: '/auth/sign-up', resetPassword: '/auth/reset-password' },
  dashboard: {
    overview: '/dashboard',
    account: '/dashboard/account',
    customers: '/dashboard/customers',
    integrations: '/dashboard/integrations',
    settings: '/dashboard/settings',
  },
  admin: {
    dashboard: '/admin/dashboard',
    productManager: '/admin/product-manager',
    categories: '/admin/product-manager/categories',
    products: '/admin/product-manager/products',
    clothing: '/admin/product-manager/clothing',
    clothingColors: '/admin/product-manager/clothing/colors',
    clothingSeasons: '/admin/product-manager/clothing/seasons',
    clothingCollections: '/admin/product-manager/clothing/collections',
    clothingSizes: '/admin/product-manager/clothing/sizes',
    clothingMaterials: '/admin/product-manager/clothing/materials',
    sales: '/admin/sales',
    purchases: '/admin/purchases',
    expenses: '/admin/expenses',
    expenseCategories: '/admin/expenses/categories',
    payments: '/admin/payments',
    paymentIn: '/admin/payments/payment-in',
    paymentOut: '/admin/payments/payment-out',
    parties: '/admin/parties',
    companies: '/admin/companies',
    stores: '/admin/stores',
  },
  stockManager: {
    dashboard: '/stock-manager/dashboard',
    parties: '/stock-manager/parties',
    suppliers: '/stock-manager/parties/suppliers',
    purchases: '/stock-manager/purchases',
    expenses: '/stock-manager/expenses',
    payments: '/stock-manager/payments',
    paymentOut: '/stock-manager/payments/payment-out',
    reports: '/stock-manager/reports',
    paymentReports: '/stock-manager/reports/payments',
    userReports: '/stock-manager/reports/users',
    expenseReports: '/stock-manager/reports/expenses',
  },
  superAdmin: {
    dashboard: '/super-admin/dashboard',
    companies: '/super-admin/companies',
    subscriptionPlans: '/super-admin/subscription-plans',
    currencies: '/super-admin/currencies',
  },
  salesman: {
    dashboard: '/salesman/dashboard',
    parties: '/salesman/parties',
    customers: '/salesman/parties/customers',
    sales: '/salesman/sales',
    paymentIn: '/salesman/sales/payment-in',
    expenses: '/salesman/expenses',
    reports: '/salesman/reports',
    paymentReports: '/salesman/reports/payments',
    userReports: '/salesman/reports/users',
    expenseReports: '/salesman/reports/expenses',
  },
  errors: { notFound: '/errors/not-found' },
} as const;
